Myapp/urls.py
from django.urls import path

from Myapp import views, testdb, beyindex

urlpatterns = [
    path('index/', views.index),
    path('zzindex/', views.zzindex),
    path('testdbadd/', testdb.testdbadd),
    path('testdblst/', testdb.testdblst),
    path('testdbupd/', testdb.testdbupd),
    path('testdoc/', testdb.testdoc),
    path('readword/', testdb.readword),
    path('lstbiao4/', testdb.lstbiao4),
    path('genbiao4/', testdb.genbiao4),
    path('changeword/', testdb.changeword),
    path('uploadfile/', testdb.uploadfile),
    path('downloadfile/', testdb.downloadfile),
    path('beyindex/', beyindex.beyindex),
    path('beybiao4/', beyindex.beybiao4),
    path('signin/', beyindex.signin),
    path('person/', beyindex.person),


    path('Bfhxiang_list/', beyindex.Bfhxiang_list),
    path('Bfhxiang_add/', beyindex.Bfhxiang_add),
    path('Bfhxiang_edit/', beyindex.Bfhxiang_edit),
    path('Bfhxiang_del/', beyindex.Bfhxiang_del),

    path('Biao72_list/', beyindex.Biao72_list),
    path('Biao72_add/', beyindex.Biao72_add),
    path('Biao72_edit/', beyindex.Biao72_edit),
    path('Biao72_del/', beyindex.Biao72_del),

    path('beee/', beyindex.beee),

    path('showhctkxx/', beyindex.showhctkxx),


    path('Bpsdwxx_list/', beyindex.Bpsdwxx_list),
    path('Bpsdwxx_add/', beyindex.Bpsdwxx_add),
    path('Bpsdwxx_edit/', beyindex.Bpsdwxx_edit),
    path('Bpsdwxx_del/', beyindex.Bpsdwxx_del),

    path('Pingshenxxb_add/', beyindex.Pingshenxxb_add),
    path('Pingshenxxb_edit/', beyindex.Pingshenxxb_edit),
    path('Pingshenxxb_del/', beyindex.Pingshenxxb_del),
    path('Pingshenxxb_list/', beyindex.Pingshenxxb_list),

    path('register/', beyindex.register),
    path('logout/', beyindex.logout),
    path('ajax_checkuser/', beyindex.ajax_checkuser),
    path('refresh_captcha/', beyindex.refresh_captcha),    # 刷新验证码，ajax




]

Mysite/urls.py
# python manage.py runserver 0.0.0.0:8000
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('Myapp.urls')),
    url(r'^static/(?P<path>.*)$',serve,{'document_root': settings.STATIC_ROOT}),
    # 图片验证码 路由
    path('captcha/', include('captcha.urls')),


]

Xzqapp/urls.py
from django.contrib import admin
from django.urls import path
from Myapp import views,testdb

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('testdbadd/',testdb.testdbadd),
    path('testdblst/',testdb.testdblst),
    path('testdbupd/',testdb.testdbupd),
    path('testdoc/',testdb.testdoc),
    path('readword/',testdb.readword),
    path('lstbiao4/',testdb.lstbiao4),
    path('genbiao4/',testdb.genbiao4),
    path('changeword/',testdb.changeword),


]

Myapp/models.py
from django.contrib.auth.models import User
from django.db import models


#
# # Assume you are activating Python 3 venv
# $ brew install mysql-client
# $ echo 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"' >> ~/.bash_profile
# $ export PATH="/usr/local/opt/mysql-client/bin:$PATH"
# $ pip install mysqlclient

# $ python3 manage.py migrate   # 创建表结构
#
# $ python3 manage.py makemigrations TestModel  # 让 Django 知道我们在我们的模型有一些变更
# $ python3 manage.py migrate TestModel   # 创建表结构

# Create your models here.
# 如果一个Story 对象既有frist_category 字段，又又second_category 字段，为确保Category 对象拥有正确的对象描述符，需要指定relate_name

# utf8_general_ci

class Students(models.Model):
    name = models.CharField(max_length=20)


class ImportFile(models.Model):
    importtype_choices = {
        ('0', u'0_读取评审通知(docx格式)'),
        ('1', u'1_读取评审报告(docx格式)'),
        ('2', u'2_评审员信息表格(docx格式)'),
        ('3', u'3_现场评审核查表(docx格式)'),
    }
    importtype = models.CharField(max_length=1, verbose_name='导入类型', choices=importtype_choices, default=0)
    file = models.FileField(upload_to='File', verbose_name='文件名')
    psxxb = models.ForeignKey('Pingshenxxb', verbose_name='评审信息ID', on_delete=models.CASCADE)  # CASCADE：此值设置，是级联删除。

    class Meta:
        verbose_name = "从文件导入数据"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.get_importtype_display()

        return str(self.importtype)


class UserInfo(models.Model):
    username = models.CharField(max_length=150, verbose_name='用户名')
    realname = models.CharField(max_length=10, verbose_name='真名')

    class Meta:
        verbose_name = "用户信息表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.username)


class PsyuanDetail(models.Model):
    name = models.CharField(max_length=8, verbose_name='姓名')
    gender = models.CharField(max_length=4, verbose_name="性别")
    danwei = models.CharField(max_length=100, verbose_name='工作单位')
    psybh = models.CharField(max_length=15, verbose_name='评审员编号')

    class Meta:
        verbose_name = "评审员个人信息表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)


class Pszcy(models.Model):
    psyzc = models.CharField(max_length=10, verbose_name="评审员组成")
    psname = models.CharField(max_length=10, verbose_name="姓名")
    ziwuzicheng = models.CharField(max_length=30, verbose_name="职务/职称")
    gzdw = models.CharField(max_length=50, verbose_name="工作单位")
    lxfs = models.CharField(max_length=18, verbose_name="联系方式")
    psxxbs = models.ManyToManyField('Pingshenxxb', verbose_name="评审通知号")
    psydtl = models.ForeignKey('PsyuanDetail', on_delete=models.CASCADE, verbose_name="评审员信息号", null=True)

    class Meta:
        verbose_name = "评审组名单"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)


class Bpsdwxx(models.Model):
    jyjcjgmc = models.CharField(max_length=100, verbose_name="检验检测机构名称", default="检验检测机构名称")
    zcdz = models.CharField(max_length=100, verbose_name="注册地址", default="注册地址")
    jydz = models.CharField(max_length=100, verbose_name="检验地址", default="检验地址")
    yzbm = models.CharField(max_length=6, verbose_name="邮编", default="邮编")
    chuanz = models.CharField(max_length=20, verbose_name="传真", default="传真")
    email = models.CharField(max_length=50, verbose_name="email", default="email")

    fzr = models.CharField(max_length=10, verbose_name="负责人", default="负责人")
    fzrzw = models.CharField(max_length=20, verbose_name="负责人职务", default="负责人职务")
    fzrgddh = models.CharField(max_length=20, verbose_name="负责人固定电话", default="负责人固定电话")
    fzryddh = models.CharField(max_length=20, verbose_name="负责人移动电话", default="负责人移动电话")

    llr = models.CharField(max_length=10, verbose_name="联络人", default="联络人")
    llrzw = models.CharField(max_length=20, verbose_name="联络人职务", default="联络人职务")
    llrgddh = models.CharField(max_length=20, verbose_name="联络人固定电话", default="联络人固定电话")
    llryddh = models.CharField(max_length=20, verbose_name="联络人移动电话", default="联络人移动电话")

    sfrdw = models.CharField(max_length=100, verbose_name="所属法人单位", default="所属法人单位")
    sfrdwdz = models.CharField(max_length=100, verbose_name="法人单位地址", default="法人单位地址")

    class Meta:
        verbose_name = "被评审单位信息表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.jyjcjgmc)


class Pingshenxxb(models.Model):
    id = models.AutoField(primary_key=True)
    pstzh = models.CharField(max_length=30, verbose_name="评审通知号", default="评审通知号")
    jcjgmc = models.CharField(max_length=100, verbose_name="检测机构名称", default="检测机构名称")
    psslh = models.CharField(max_length=50, verbose_name="受理号", default="受理号")
    sqsx = models.CharField(max_length=50, verbose_name="申请事项", default="申请事项")
    psdate = models.CharField(max_length=30, verbose_name="评审时间", default="评审时间")
    psadress = models.CharField(max_length=100, verbose_name="评审地点", default="评审地点")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户Id", null=True)
    bpsdwxx = models.ForeignKey('Bpsdwxx', on_delete=models.CASCADE, verbose_name="被评审单位Id", null=True)
    userinfo = models.ManyToManyField('UserInfo')

    class Meta:
        verbose_name = "评审任务信息总表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.pstzh)


class Biao4(models.Model):
    psxxb = models.ForeignKey('Pingshenxxb', on_delete=models.CASCADE)
    lyxh = models.CharField(max_length=20, verbose_name="领域序号")
    lyname = models.CharField(max_length=100, verbose_name="领域")
    lbxh = models.CharField(max_length=20, verbose_name="类别序号")
    lb = models.CharField(max_length=100, verbose_name="类别")
    dxxh = models.CharField(max_length=20, verbose_name="对象序号")
    duixiang = models.CharField(max_length=100, verbose_name="检测对象")
    xmxh = models.CharField(max_length=20, verbose_name="参数序号")
    xmmc = models.CharField(max_length=100, verbose_name="参数名称")
    csmc = models.CharField(max_length=100, verbose_name="参数名称")
    yjbz = models.CharField(max_length=300, verbose_name="依据的标准（方法）名称及编号（含年号）")
    xzfw = models.CharField(max_length=100, verbose_name="限制范围")
    sm = models.CharField(max_length=200, verbose_name="说明")

    class Meta:
        verbose_name = "建议批准的检验检测能力表 表4"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.csmc


class Biao5(models.Model):
    psxxb = models.ForeignKey('Pingshenxxb', on_delete=models.CASCADE)  # CASCADE：此值设置，是级联删除。
    xuhao = models.CharField(max_length=2, verbose_name="序号")
    name = models.CharField(max_length=10, verbose_name="姓名")
    ziwuzicheng = models.CharField(max_length=30, verbose_name="职务/职称")
    sqqzly = models.CharField(max_length=500, verbose_name="授权签字领域")
    beizu = models.CharField(max_length=300, verbose_name="备注")

    class Meta:
        verbose_name = "建议批准的授权签字人 表5"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# If the model field has blank=True, then required is set to False on the form field. Otherwise,
# required=True.
BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))
class Biao72(models.Model):
    psxxb = models.ForeignKey('Pingshenxxb', on_delete=models.CASCADE)
    xuhao = models.CharField(max_length=4, verbose_name="序号")
    xmmc = models.CharField(max_length=100, verbose_name="检测类别项目或产品名称",blank=True)

    yjbz = models.CharField(max_length=300, verbose_name="依据标准及代号")
    xmxh = models.CharField(max_length=20, verbose_name="参数序号")
    csmc = models.CharField(max_length=100, verbose_name="参数名称")
    yjbztk = models.CharField(max_length=300, verbose_name="标准条款号")
    xcsy = models.BooleanField(verbose_name="现场试验", default=False)
    nlyz = models.BooleanField(verbose_name="利用能力验证结果", default=False,)
    clsh = models.BooleanField(verbose_name="测量审核盲样试验", default=False)
    bdjg = models.BooleanField(verbose_name="利用实验室间比对结果", default=False)
    xcys = models.BooleanField(verbose_name="现场演示", default=False)
    xctw = models.BooleanField(verbose_name="现场提问", default=False)
    cyjlbg = models.BooleanField(verbose_name="查阅记录和报告", default=True)
    hcyq = models.BooleanField(verbose_name="核查仪器设备配置", default=True)
    sfqr = models.BooleanField(verbose_name="是否确认(Y/N)", default=False)
    beizu = models.CharField(max_length=200, verbose_name="备注")

    class Meta:
        verbose_name = "现场评审能力确认方式及确认结果一览表 表7-2"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.csmc


class Xcpshcb(models.Model):
    zhangbh = models.CharField(max_length=3, verbose_name="条款章号")
    zhangmc = models.CharField(max_length=8, verbose_name="条款章名")
    tkhao = models.CharField(max_length=10, verbose_name="条款号")
    psneirong = models.CharField(max_length=1000, verbose_name="评审内容")

    class Meta:
        verbose_name = "检验检测机构资质认定现场评审核查表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tkhao


class Xcpshcb71(models.Model):
    psxxb = models.ForeignKey('Pingshenxxb', verbose_name="评审通知号", on_delete=models.CASCADE, null=True)
    pshcxx = models.ForeignKey('Xcpshcb', verbose_name="核查信息", on_delete=models.CASCADE, null=True)
    psjd = models.CharField(max_length=1, verbose_name="不符合阶段")
    psdate = models.DateField(verbose_name="日期", auto_now=True)
    psjg = models.CharField(max_length=1, verbose_name="评审结果")
    psyj = models.CharField(max_length=500, verbose_name="依据")
    pssm = models.CharField(max_length=500, verbose_name="评审说明")
    jzfs = models.CharField(max_length=1, verbose_name="纠正确认方式")
    bsfyj = models.CharField(max_length=1, verbose_name="被评审方确认意见")
    pszzyj = models.CharField(max_length=1, verbose_name="评审组长确认意见")

    class Meta:
        verbose_name = "现场评审核查表7.1"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.psjg


class Bfhxiang(models.Model):
    psxxb = models.ForeignKey('Pingshenxxb', verbose_name="评审通知号", on_delete=models.CASCADE, null=True)

templates/Bfhxiang-edit.html
{% extends "bey-base.html" %}
{% block mainbody %}

    <div class="page-content">
        <!-- 面包屑导航 -->
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="#">资质评审</a>
                </li>
                <li class="active">不符合项信息</li>
            </ul>
        </div>
        <!-- /面包屑导航 -->
        <!-- 页面主体 -->
        <form action="" method="Post" novalidate>
            {% csrf_token %}
            <div class="page-body">

                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <div class="widget">
                            <div class="widget-header bordered-top bordered-palegreen">
                                <span class="widget-caption">不符合信息编辑</span>
                            </div>

                            <div class="widget-body">
                                <div class="collapse in">

                                    {% for field in form %}
                                        <div class="row">
                                            <div class="form-group">
                                                <div class="col-xs-3 col-sm-3 col-md-3 ">
                                                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                                                </div>
                                              <div class="col-xs-5 col-md-5 col-sm-5">
                                                {% if field.name == 'bfhxwcdate' %}
                                                    <div>
                                                        <div class="input-group">
                                                            <input class="form-control date-picker"
                                                                   id="id-date-picker-1" type="text"
                                                                   data-date-format="yyyy-mm-dd">
                                                            <span class="input-group-addon">
                                                               <i class="fa fa-calendar"></i>
                                                            </span>
                                                        </div>
                                                    </div>

                                                {% else %}


                                                        <div>{{ field }}</div>

                                                {% endif %}
                                               </div>
                                                <div class="col-xs-4 col-md-4 col-sm-4">
                                                    <span>{{ field.errors.0 }}</span>
                                                </div>
                                            </div>
                                            {% if field.label == "条款号" %}
                                                <div class="row">
                                                    <div class="form-group">
                                                        <div class="col-xs-3 col-sm-3 col-md-3 ">

                                                            <select class="tkzj" id="e1" onchange="showhctk(this)">

                                                                {% for field in hcblst %}
                                                                    <option value={{ field.zhangbh }}>
                                                                    {{ field.zhangbh }} {{ field.zhangmc }}
                                                                {% endfor %}
                                                            </select>

                                                        </div>
                                                        <div class=" col-xs-9 col-sm-9 col-md-9 ">

                                                            <select class="tkjn" id="e2" onchange="selecthctk(this)">


                                                                <option value="AL">
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endif %}

                                        </div>

                                    {% endfor %}

                                </div>
                                <div class="row"><input style="margin-right: 80px" class="btn btn-primary pull-right"
                                                        type="submit"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>






    <!-- /页面主体 -->


{% endblock %}

templates/aa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--头部a区域 -->
<header></header>
<!--/头部区域 -->
{#头部区域#}
<section></section>
{#/头部区域#}
{#头部区域#}
<section></section>
{#/头部区域#}
{#头部区域#}
<section></section>
{#/头部区域#}
{#头部区域#}
<section></section>
{#/头部区域#}
{#头部区域#}
<section></section>
{#/头部区域#}
{#头部区域#}
<section></section>
{#/头部区域#}
{#头部区域#}
<footer></footer>
{#/头部区域#}


</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>资质评审报告管理</title>
    <title>Bootstrap 实例 - 默认的导航栏</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/mycss.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

{#navbar-fixed-top#}
<nav class="navbar navbar-default navbar-inverse " role="navigation" style="padding: 5px;margin-bottom: 5px">
    <div class="container">
{#    <div class="container-fluid">#}
        <div class="navbar-header col-md-2 hidden-sm hidden-xs">
            <a class="navbar-brand" href="/myapp/index/">主页</a>
        </div>
        <div class="col-md-10">
            <ul class="nav navbar-nav">
                <li  class="active col-sm-4 col-xs-4 "><a href="/myapp/readword/">读取word</a></li>
                <li class="col-sm-4 col-xs-4"><a href="/myapp/lstbiao4/?page=1">表4列表</a></li>
                <li class="col-sm-4 col-xs-4"><a href="/myapp/genbiao4/">生成表4</a></li>
                <li class="col-sm-4 col-xs-4"><a href="/myapp/uploadfile/">传递文件</a></li>
                <li class="col-sm-4 col-xs-4"><a href="/myapp/index/">返回首页</a></li>

                <li class="dropdown col-sm-4 col-xs-4">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        系统工具
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin/">管理工具</a></li>
                        <li><a href="/myapp/changeword/">改变word文档内容</a></li>
                        <li><a href="#">Jasper Report</a></li>
                        <li class="divider"></li>
                        <li><a href="#">分离的链接</a></li>
                        <li class="divider"></li>
                        <li><a href="#">{{ hello }}</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="content" style="padding: 1px;margin: 10px">
{% block mainbody %}
{% endblock %}
</div>
</body>
</html>

templates/bey-page.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="UTF-8">
    <title>自己页面</title>
    <meta name="description" content="Dashboard"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" href="/static/lib/beyond/img/favicon.png" type="image/x-icon">
    <!-- 基本样式表 -->
    <link href="/static/lib/beyond/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/static/lib/beyond/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/static/lib/beyond/css/dataTables.bootstrap.css" rel="stylesheet"/>
    <!-- 自定义样式表 -->
    <link id="beyond-link" href="/static/lib/beyond/css/beyond.min.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/beypage.css" rel="stylesheet">


</head>
<body>


{% block mainbody %}
    <div class="page-content">
        <!-- 面包屑导航 -->
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="#">资质评审</a>
                </li>
                <li class="active">表4列表</li>
            </ul>
        </div>
        <!-- /面包屑导航 -->
        <!-- 页面主体 -->
        <div class="page-body">
            <div class="row">
                <h2>请选择菜单</h2>
            </div>
            <!-- \row -->
        </div>
        <!-- /页面主体 -->
    </div>
{% endblock %}

<!-- 基本js -->
<script src="/static/lib/beyond/js/jquery-2.0.3.min.js"></script>
<script src="/static/lib/beyond/js/bootstrap.min.js"></script>
<!-- 自定义js -->
<script src="/static/lib/beyond/js/beyond.min.js"></script>
<script src="/static/js/beypage.js"></script>

</body>
</html>

templates/bpsdwxx-edit.html
{% extends "bey-base.html" %}
{% block mainbody %}

    <div class="page-content">
        <!-- 面包屑导航 -->
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="#">资质评审</a>
                </li>
                <li class="active">被评审单位信息</li>
            </ul>
        </div>
        <!-- /面包屑导航 -->
        <!-- 页面主体 -->
        <form action="/myapp/add_Bpsdwxx/" method="Post" novalidate>
            {% csrf_token %}


            <div class="widget">
                <div class="widget-header bordered-top bordered-palegreen">
                    <span class="widget-caption">Default Inputs</span>
                </div>
                <div class="widget-body">
                    <div class="collapse in">
                        <form role="form">

                            {% for field in form %}
                                <div class="row">
                                    <div class="col-xs-3 col-sm-3 col-md-3 ">
                                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                                    </div>
                                    <div class="col-xs-5 col-md-5 col-sm-5">
                                        <div>{{ field }}</div>
                                    </div>
                                    <div class="col-xs-4 col-md-4 col-sm-4"><span>{{ field.errors.0 }}</span>
                                    </div>
                                </div>
                            {% endfor %}

                            <div class="row" ><input style="margin-right: 80px" class="btn btn-primary pull-right" type="submit"></div>
                        </form>
                    </div>
                </div>
            </div>


        </form>


        <!-- /页面主体 -->
    </div>

{% endblock %}

templates/downloadfile.html
{#下载  文件#}
{% extends "base.html" %}
{% block mainbody %}
    <a href="/myapp/download/">
                                        <button class="btn bg-danger">下载</button>
                                      </a>
{{ msg }}
{% endblock mainbody %}

templates/psxxb-edit.html
{% extends "bey-base.html" %}
{% block mainbody %}

    <div class="page-content">
        <!-- 面包屑导航 -->
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="#">资质评审</a>
                </li>
                <li class="active">评审任务信息</li>
            </ul>
        </div>
        <!-- /面包屑导航 -->
        <!-- 页面主体 -->
        <form action="" method="Post" novalidate>
            {% csrf_token %}


            <div class="widget">
                <div class="widget-header bordered-top bordered-palegreen">
                    <span class="widget-caption">Default Inputs</span>
                </div>
                <div class="widget-body">
                    <div class="collapse in">
                        <form role="form">

                            {% for field in form %}
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-xs-3 col-sm-3 col-md-3 ">
                                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                                        </div>
                                        <div class="col-xs-5 col-md-5 col-sm-5" >
                                            <div>{{ field }}</div>
                                        </div>
                                        <div class="col-xs-4 col-md-4 col-sm-4"><span>{{ field.errors.0 }}</span>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                            <div class="row"><input style="margin-right: 80px" class="btn btn-primary pull-right"
                                                    type="submit"></div>
                        </form>
                    </div>
                </div>
            </div>


        </form>


        <!-- /页面主体 -->
    </div>

{% endblock %}

templates/signin.html
{% extends "bey-page.html" %}
{% block mainbody %}
    <form action="/myapp/signin/" method="POST">
        <div class="login-container animated fadeInDown">
            <div class="loginbox bg-white">
                <div class="loginbox-title">登 陆</div>
                <div class="loginbox-social">
                    <div class="social-title ">使用你的社交账户登录</div>
                    <div class="social-buttons">
                        <a href="" class="button-facebook">
                            <i class="social-icon fa fa-facebook"></i>
                        </a>
                        <a href="" class="button-twitter">
                            <i class="social-icon fa fa-twitter"></i>
                        </a>
                        <a href="" class="button-google">
                            <i class="social-icon fa fa-google-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="loginbox-or">
                    <div class="or-line"></div>
                    <div class="or">或者</div>
                </div>
                <div class="loginbox-textbox">
                    <input type="text" class="form-control" name="username" placeholder="用户名">
                </div>
                <div class="loginbox-textbox">
                    <input type="password" name="password" class="form-control" placeholder="密码">
                </div>
                <div class="loginbox-forgot">
                    <a href="">忘记密码?</a>
                </div>
                <div class="loginbox-submit">
                    <input type="submit" class="btn btn-primary btn-block" value="登录">
                </div>
                <div class="loginbox-signup">
                    <a href="/myapp/register/">注册新用户</a>
                </div>
            </div>
            <div class="logobox">


            </div>
        </div>
    </form>
{% endblock %}

templates/teee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form>
                                <input type="radio" name="nlyz1"  id="id_nlyz">11111 <br>
                                <input type="radio" name="nlyz2" id="id_nlyz">22222 <br>
                                <input type="radio" name="nlyz3" id="id_nlyz">333333 <br>
                                <input class="checkbox-slider toggle colored-blue" type="checkbox">dddf<br>
                            </form>
</body>
</html>